### ISSUE TITLE
Add beacons on objective-based maps to represent objective locations

### ISSUE THREAD

**Issue by Palmidence** [WarzoneMC/Maps#24]
Makes it easier for players to know where objectives are, especially if they are new. It also helps to see from long distances exactly where the objective would be. This is a good idea especially because of players constantly wondering where the objective is, among many maps.

**Comment by Crnsxx** [comment]
@Palmidence u mean like on every map there is an Beacon (Under the Objective) right?

**Comment by Virtualizes** [comment]
He means that a beacon will be under the objective of the certain map. 
For example; on a CTW map, a beacon will be there to signal that its an objective. I'm pretty sure the majority or all of the DTW maps have a beacon at the wool.

Also, perhaps there could be a tutorial at the start of the game that can be disabled or enabled.
Basically, similar to HiveMC; they have a system to give newcomers a tutorial to the match unless it is disabled. The timer might have to be increased in order to do this, or they would be presented with a message where the player can hover over it and it will greet them with what to do.
